# Generated by Django 5.0.1 on 2026-01-02 16:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='ocr/documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff', 'bmp', 'gif', 'webp'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA256 hash of file content for duplicate detection', max_length=64)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('language', models.CharField(default='eng', help_text='OCR language code', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When document was archived', null=True)),
            ],
            options={
                'verbose_name': 'OCR Document',
                'verbose_name_plural': 'OCR Documents',
                'db_table': 'ocr_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='ocr_documen_uploade_edda1f_idx'), models.Index(fields=['file_hash', 'is_deleted'], name='ocr_documen_file_ha_460c43_idx'), models.Index(fields=['status', 'is_deleted'], name='ocr_documen_status_a832fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('extracted_text', models.TextField(help_text='Full extracted text')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('extraction_method', models.CharField(choices=[('text_extraction', 'Text Extraction'), ('ocr', 'OCR'), ('hybrid', 'Hybrid')], help_text='Method used for text extraction', max_length=20)),
                ('language', models.CharField(help_text='Language used for extraction', max_length=10)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Average OCR confidence score (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ocr.ocrdocument')),
            ],
            options={
                'verbose_name': 'OCR Result',
                'verbose_name_plural': 'OCR Results',
                'db_table': 'ocr_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFPageResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('extracted_text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('extraction_method', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.ocrresult')),
            ],
            options={
                'verbose_name': 'PDF Page Result',
                'verbose_name_plural': 'PDF Page Results',
                'db_table': 'ocr_pdf_page_result',
                'ordering': ['result', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='OCRProcessingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Additional structured data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ocr.ocrdocument')),
            ],
            options={
                'verbose_name': 'OCR Processing Log',
                'verbose_name_plural': 'OCR Processing Logs',
                'db_table': 'ocr_processing_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='ocr_process_documen_6e4c01_idx'), models.Index(fields=['level', '-created_at'], name='ocr_process_level_076120_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['document', '-created_at'], name='ocr_result_documen_a4d3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfpageresult',
            index=models.Index(fields=['result', 'page_number'], name='ocr_pdf_pag_result__d46ee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfpageresult',
            unique_together={('result', 'page_number')},
        ),
    ]
